  package:
  name: nhalbach
  version: "0.2"

source:
  git_url: https://github.com/PoloMag/nhalbach.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - docopt
    - pandas



about:
  home: https://github.com/PoloMag/nhalbach
  summary: "Tools for simulating nested Halbach cylinders"
  license_file: LICENSE.md
